# Generated by Django 3.0.4 on 2020-05-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_route', '0004_auto_20200510_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='days',
        ),
    ]
