# Generated by Django 3.0.4 on 2020-05-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_route', '0006_auto_20200510_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripplaces',
            name='city',
        ),
    ]
