# Generated by Django 3.0.4 on 2020-05-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_route', '0008_trip_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='start_city',
            field=models.CharField(default=1, max_length=215),
            preserve_default=False,
        ),
    ]
